"use client";

import { useEffect, useState } from "react";
import { Bot, CheckCircle2, Loader2, Send, Wrench } from "lucide-react";
import { api, ApiError, type AgentInfo, type AgentReply } from "@/lib/api";
import { Card, Pill } from "../ui";

export function AgentsView() {
  const [agents, setAgents] = useState<AgentInfo[]>([]); const [command, setCommand] = useState(""); const [reply, setReply] = useState<AgentReply | null>(null); const [loading, setLoading] = useState(true); const [running, setRunning] = useState(false); const [error, setError] = useState("");
  useEffect(() => { api.agents().then(setAgents).finally(() => setLoading(false)); }, []);
  async function run() { if (!command.trim()) return; setRunning(true); setError(""); try { setReply(await api.runAgentCommand(command)); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Agent workflow failed"); } finally { setRunning(false); } }
  return <div className="space-y-5"><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-violet-600">AI control plane</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">AI workforce</h2><p className="mt-1 text-xs text-[#858c97]">Run auditable HR workflows and inspect specialist health.</p></div><Card className="border-violet-200/60 bg-gradient-to-r from-white to-violet-50 p-5"><div className="flex gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#17191f] text-violet-300"><Bot size={18} /></div><div className="flex-1"><p className="text-xs font-semibold">Delegate to Aurora</p><div className="mt-3 flex rounded-xl border border-black/[.08] bg-white p-1.5"><input value={command} onChange={(event) => setCommand(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void run(); }} className="min-w-0 flex-1 px-2 text-xs outline-none" placeholder="e.g. Who is absent today?" /><button disabled={running} onClick={() => void run()} className="grid size-8 place-items-center rounded-lg bg-[#765cf4] text-white">{running ? <Loader2 size={13} className="animate-spin" /> : <Send size={13} />}</button></div>{error && <p className="mt-2 text-xs text-red-600">{error}</p>}{reply && <div className="mt-4 rounded-xl bg-white p-4"><div className="flex items-center gap-2"><Pill tone="violet">{reply.agent}</Pill><span className="mono text-[8px] text-[#989ea7]">{reply.task_id}</span></div><p className="mt-3 text-xs leading-5 text-[#555d68]">{reply.message}</p><p className="mt-2 text-[9px] text-[#9298a1]">{reply.explainability}</p></div>}</div></div></Card>{loading ? <div className="grid h-48 place-items-center"><Loader2 className="animate-spin text-violet-600" /></div> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{agents.map((agent) => <Card key={agent.name} className="p-5"><div className="flex items-center justify-between"><div className="grid size-9 place-items-center rounded-xl bg-violet-100 text-violet-700"><Bot size={15} /></div><Pill tone="green">{agent.status}</Pill></div><h3 className="mt-4 text-sm font-semibold">{agent.name}</h3><p className="mt-1 min-h-10 text-[10px] leading-5 text-[#858c97]">{agent.purpose}</p><div className="mt-4 grid grid-cols-2 gap-2 border-t border-black/[.05] pt-3 text-[9px] text-[#737b87]"><span className="flex items-center gap-1"><CheckCircle2 size={10} />{agent.success_rate}% success</span><span className="flex items-center gap-1"><Wrench size={10} />{agent.tools.length} tools</span></div></Card>)}</div>}</div>;
}

